### ISSUE TITLE
Unable to load resource org/monarchinitiative/fenominal/core/impl/lexical/clusters

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/fenominal#91]
From another application, I see that it is not able to load the clusters file from the library.
Presumably something is wrong with the way the resources are being loaded into the jar file.
check on this
```
(o.m.phenotefx.gui.PhenoteController[ERROR] 08:53:24.092 [JavaFX Application Thread]  
(o.m.f.c.i.lexical.LexicalResourcesjava.lang.IllegalStateException: 
Unable to load resource org/monarchinitiative/fenominal/core/impl/lexical/clusters
```

**Comment by cmungall** [comment]
I am getting this too, even without the UI

```
git clone git@github.com:monarch-initiative/fenominal.git
mvn install
java -jar fenominal-cli/target/fenominal.jar D
java -jar fenominal-cli/target/fenominal.jar P -i test.txt
```

gives

```
11:55:43.279 ERROR o.m.f.c.i.lexical.LexicalResources - Unable to load resource org/monarchinitiative/fenominal/core/impl/lexical/clusters
java.lang.IllegalStateException: Unable to load resource org/monarchinitiative/fenominal/core/impl/lexical/clusters
	at org.monarchinitiative.fenominal.core.impl.lexical.LexicalResources.getResourceAsBufferedReader(LexicalResources.java:163)
	at org.monarchinitiative.fenominal.core.impl.lexical.LexicalResources.loadLexicalClusters(LexicalResources.java:77)
	at org.monarchinitiative.fenominal.core.impl.lexical.LexicalResources.<init>(LexicalResources.java:34)
	at org.monarchinitiative.fenominal.core.impl.FuzzyTermMiner.<init>(FuzzyTermMiner.java:30)
	at org.monarchinitiative.fenominal.core.TermMiner.defaultFuzzyMapper(TermMiner.java:41)
	at org.monarchinitiative.fenominal.cli.analysis.PassageParser.<init>(PassageParser.java:38)
	at org.monarchinitiative.fenominal.cli.cmd.ParseCommand.call(ParseCommand.java:37)
	at org.monarchinitiative.fenominal.cli.cmd.ParseCommand.call(ParseCommand.java:10)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.monarchinitiative.fenominal.cli.Main.main(Main.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
11:55:43.287 ERROR o.m.f.c.i.lexical.LexicalResources - Unable to load resource org/monarchinitiative/fenominal/core/impl/lexical/tblat_optimal_thresholds
...
11:55:44.008 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0031974]: increased vertical cup-to-disc ratio - 0.6
11:55:44.008 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0031975]: increased vertical cup-to-disc ratio - 0.7
11:55:44.021 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0030558]: best corrected visual acuity 0.5 logmar
11:55:44.029 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0010848]: eeg with spike-wave complexes (2.5-3.5 hz)
11:55:44.031 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0030574]: pinhole visual acuity 0.6 logmar
11:55:44.034 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0005376]: recurrent h. influenzae infections
11:55:44.034 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0030543]: unaided visual acuity 0.8 logmar
11:55:44.041 WARN  o.m.f.core.impl.kmer.KmerGenerator - Unable to process term [0030545]: unaided visual acuity 1.0 logmar
```

and writes an empty file
