### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/fenominal#97]
I can compile and build the latest fenominal without problems. However, when I try to run

org.monarchinitiative.fenominal.core.hpo.ReportParseTest

in the test/java, I get a weird error

```
java.lang.IllegalAccessError: class org.monarchinitiative.phenol.io.MinimalOntologyLoader (in unnamed module @0x7c417213) cannot access class org.monarchinitiative.phenol.ontology.data.impl.SimpleMinimalOntology (in module org.monarchinitiative.phenol.core) because module org.monarchinitiative.phenol.core does not export org.monarchinitiative.phenol.ontology.data.impl to unnamed module @0x7c417213

	at org.monarchinitiative.phenol.io.MinimalOntologyLoader.loadOntology(MinimalOntologyLoader.java:95)
	at org.monarchinitiative.phenol.io.MinimalOntologyLoader.loadOntology(MinimalOntologyLoader.java:63)
	at org.monarchinitiative.phenol.io.MinimalOntologyLoader.loadOntology(MinimalOntologyLoader.java:45)
	at org.monarchinitiative.phenol.io.MinimalOntologyLoader.loadOntology(MinimalOntologyLoader.java:36)
	at org.monarchinitiative.fenominal.core@0.7.12-SNAPSHOT/org.monarchinitiative.fenominal.core.TestResources.hpo(TestResources.java:18)
	at org.monarchinitiative.fenominal.core@0.7.12-SNAPSHOT/org.monarchinitiative.fenominal.core.hpo.ReportParseTest.<clinit>(ReportParseTest.java:33)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

The POM file uses dependency and plugin management.

**Comment by ielis** [comment]
I assume you are using IntelliJ to run the test by clicking on the green triangle on the gutter because I get the same error when I run it.

However, the error is gone when I select *Do not use --module-path option*:
![Screenshot_20240401_132640](https://github.com/monarch-initiative/fenominal/assets/12170955/9bcde2c6-65dd-46c8-a708-2c3c87623221)


So, I assume this is the issue.

I will close this but please reopen if the problem persists.

**Comment by pnrobinson** [comment]
Thanks. I am probably still a little confused about module path vs CP, but given we are trying to test public functions, shouldn't this also be on the MP? Anyway, not a critical thing

**Comment by ielis** [comment]
I think this is because testing is done in a different way than what we do when we run an app. 

I believe IntelliJ invokes JUnit runner with module path options, including creation of an unnamed module for the test code. Then, in presence of an unnamed module, the code explodes.

We do not have the issues when we use the code in a "proper" modular app or from class path:

- We do not have an *unnamed* module in a proper modular app, so it works
- When running with class path options (`-cp` or `-jar`), we have no modules whatsoever, so there is no illegal access.


But this is just my best guess, I am not 100% sure and I will not investigate this further for the sake of time.
